name: 'Scan Repository'
description: 'Scan repository for vulnerabilities'
inputs:
  report-path:
    description: 'Output file name'
    required: false
    default: 'trivy-repository.report'
  report-format:
    description: 'Report format (sarif, json, table)'
    required: false
    default: 'table'
  severity:
    description: 'Severity level (UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL)'
    required: false
    default: 'CRITICAL,HIGH'
  fail-on-vulns:
    description: 'Fail build on found vulnerabilities'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Generate Trivy Vulnerability Report
      uses: aquasecurity/trivy-action@0.29.0
      id: scan
      with:
        scan-type: "fs"
        output: ${{ inputs.report-path }}
        format: ${{ inputs.report-format }}
        severity: ${{ inputs.severity }}
        scan-ref: .
        exit-code: 1
      continue-on-error: true

    - name: Upload Vulnerability Scan Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: trivy-repository
        path: $${{ inputs.report-path }}
        retention-days: 30

    - name: Fail on vulnerabilities
      if: steps.scan.outcome != 'success' && inputs.fail-on-vulns == 'true'
      shell: bash
      run: exit 1
