name: 'Scan Image'
description: 'Scan an image for vulnerabilities'
inputs:
  report-name:
    description: 'Report name'
    required: false
    default: 'trivy-image'
  report-filename:
    description: 'Report filename'
    required: false
    default: 'trivy-image.report'
  aws-access-key-id:
    description: 'AWS Key ID secret name'
    required: true
  aws-secret-access-key:
    description: 'AWS Access Key secret name'
    required: true
  region:
    description: 'AWS region'
    required: false
    default: 'us-east-1'
  registry:
    description: 'ECR image repository'
    required: true
  image:
    description: 'ECR image name & tag'
    required: true
  report-format:
    description: 'Report format (sarif, json, table)'
    required: false
    default: 'table'
  severity:
    description: 'Severity level (UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL)'
    required: false
    default: 'CRITICAL,HIGH'
  fail-on-vulns:
    description: 'Fail build on found vulnerabilities'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.region }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Generate Trivy Vulnerability Report
      uses: aquasecurity/trivy-action@0.29.0
      id: scan
      with:
        scan-type: 'image'
        image-ref: '${{ inputs.registry }}/${{ inputs.image }}'
        output: ${{ inputs.report-filename }}
        format: ${{ inputs.report-format }}
        severity: ${{ inputs.severity }}
        exit-code: 1
      continue-on-error: true

    - name: Upload Vulnerability Scan Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.report-name }}
        path: ${{ inputs.report-filename }}
        retention-days: 30

    - name: Fail on vulnerabilities
      if: steps.scan.outcome != 'success' && inputs.fail-on-vulns == 'true'
      shell: bash
      run: exit 1
