name: 'ECR & K8s login'
description: 'Use org secrets as credentials for ECR login and kubeconfig setup'
inputs:
  aws-access-key-id:
    description: 'AWS Key ID secret name'
    required: true
  aws-secret-access-key:
    description: 'AWS Access Key secret name'
    required: true
  env:
    required: true
  registry:
    required: true
  region:
    description: 'AWS region'
    required: true
  kubeconfig:
    description: 'base64 encoded kubeconfig'
    required: true

runs:
  using: "composite"
  steps:
    - name: Login ECR
      # NOTE WELL: the ECR region is hard-coded to us-east-1 as this is unlikely to change.
      # If there is ever actually a need to change it, let's use a dedicated `ecr-region` var
      # to accept this config to avoid conflict with our `env` & `region` K8s cluster config.
      run: |
          export AWS_ACCESS_KEY_ID=${{ inputs.aws-access-key-id }}
          export AWS_SECRET_ACCESS_KEY=${{ inputs.aws-secret-access-key }}
          export AWS_DEFAULT_REGION=${{ inputs.region }}
          aws ecr get-login-password --region inputs.region | docker login \
          --username AWS --password-stdin ${{ inputs.registry }}
      shell: bash
    - name: Setup kubeconfig file
      env:
        ORG_KUBECONFIG: ${{ inputs.kubeconfig }}
      run: |
          base64 --decode <<<"${!KUBECONFIG}" >./kubeconfig
      shell: bash
