
name: 'Docker Build & Push'
description: 'Performs an ECR login and docker build/push after'
inputs:
  aws-access-key-id:
    description: 'AWS Key ID secret name'
    required: true
  aws-secret-access-key:
    description: 'AWS Access Key secret name'
    required: true
  region:
    description: 'AWS region'
    required: true
  registry:
    description: 'ECR image repository'
    required: true
  file:
    description: 'Dockerfile path (e.g. build/Dockerfile)'
    required: false
    default: build/Dockerfile
  target:
    description: 'Dockerfile stage target'
    required: false
    default: 'release'
  tags:
    description: 'List of tags'
    required: true
  docker-build-args:
    description: 'Additional argument to pass to docker build'
    required: false

runs:
  using: "composite"
  steps:
    - name: Login ECR
      run: |
          export AWS_ACCESS_KEY_ID=${{ inputs.aws-access-key-id }}
          export AWS_SECRET_ACCESS_KEY=${{ inputs.aws-secret-access-key }}
          export AWS_DEFAULT_REGION=${{ inputs.region }}
          aws ecr get-login-password --region ${{ inputs.region }} | docker login \
          --username AWS --password-stdin ${{ inputs.registry }}
      shell: bash

    - name: Docker Deps
      run: |
        docker build ${{ inputs.docker_build_args }} -t ${{ inputs.registry }}:deps -f ${{ inputs.file }} .
      shell: bash

    - name: Docker Build
      env:
        target: ${{ inputs.target }}
        tags: ${{ inputs.tags }}
        registry: ${{ inputs.registry }}
        dockerfile: ${{ inputs.file }}
      run: |
        chmod +x ${{ github.action_path }}/build-push.sh
        ${{ github.action_path }}/build-push.sh
      shell: bash
