name: Build Docker
on:
  workflow_call:
    inputs:
      region:
        required: false
        type: string
        default: 'us-east-1'
        description: 'AWS region'
      tags:
        required: true
        type: string
        description: 'Docker build tags'
      registry:
        required: true
        type: string
        description: 'Registry image name'
      dockerfile_path:
        required: false
        type: string
        default: build/Dockerfile
        description: 'Dockerfile relative path'
      docker_target:
        required: false
        type: string
        default: ''
        description: 'Dockerfile target'

    secrets:
      API_TOKEN_GITHUB:
        required: true
        description: 'Github token hash'
      AWS_ACCESS_KEY_ID:
        required: true
        description: 'AWS access key id'
      AWS_SECRET_ACCESS_KEY:
        required: true
        description: 'AWS secret access key'

jobs:
  release:
    name: Build Docker
    runs-on: "non-prod"
    steps:
    - name: Setup | Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
        token: ${{ secrets.API_TOKEN_GITHUB }}

    - name: Docker | Build and Push
      uses: timescale/cloud-actions/build-push@main
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: ${{ inputs.region }}
        tags: |
          ${{ inputs.tags }}
        registry: ${{ inputs.registry }}
        target: ${{ inputs.docker_target }}
        file: ${{ inputs.dockerfile_path }}
