name: Workflow linter
on:
  push:
    paths:
      - '.github/workflows/*'

jobs:
  workflow-linter:
    runs-on: ubuntu-latest
    name: Workflow linter
    steps:

    - name: Setup | Checkout submodules
      uses: actions/checkout@v3

    - name: Get modified files
      id: files
      uses: jitterbit/get-changed-files@v1
      continue-on-error: true
  
    - uses: reviewdog/action-actionlint@v1
      with: 
        actionlint_flags: -ignore SC2086 -config-file .github/actionlint.yaml
        fail_on_error: true
        level: error

    #- name: Download action linter
    #  run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)

    - name: Run action linter
      run: |
        ./actionlint \
          ${{ steps.files.outputs.all }}
          
